services:
  api1: &api
    build: ./app
    hostname: api1
    container_name: api1
    environment:
      - PORT=3333
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - QUEUE_CONCURRENCY=20
      - SOCKET_PATH=/tmp/sockets/api1.sock
    volumes:
      - ./sockets:/tmp/sockets
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "135MB"

  api2:
    <<: *api
    hostname: api2
    container_name: api2
    environment:
      - PORT=3333
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - QUEUE_CONCURRENCY=20
      - SOCKET_PATH=/tmp/sockets/api2.sock

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "20000",
        "--tcp-backlog",
        "511",
        "--dynamic-hz",
        "yes",
      ]
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "65MB"

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - "5540:5540"
  #   networks:
  #     - backend

  load-balancer:
    image: nginx:1.25.2-alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sockets:/tmp/sockets
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "15MB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets:
