services:
  api1:
    build: ./app
    hostname: api1
    environment:
      - DATABASE_HOST=db
      - PORT=3333
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - backend
      - payment-processor
    depends_on:
      - db

  api2:
    build: ./app
    hostname: api2
    environment:
      - DATABASE_HOST=db
      - PORT=3333
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - backend
      - payment-processor
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    hostname: db
    environment:
      - POSTGRES_DB=rinha_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  load-balancer:
    image: nginx:1.25.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
