name: On push to main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run semantic-release manually
        run: |
          npx semantic-release \
            --plugins @semantic-release/commit-analyzer \
                      @semantic-release/release-notes-generator \
                      @semantic-release/github

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push_docker:
    name: Build e Push da Imagem Docker
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            lhuizf/rinha-de-backend-2025-bun:latest
            lhuizf/rinha-de-backend-2025-bun:${{ steps.get_tag.outputs.tag }}
